server:
  port: 8003 #指定运行端口
spring:
  application:
    name: eureka-server #指定服务名称
eureka:
  instance:
    hostname: replica2 #指定主机地址
  client:
    service-url:
      defaultZone: http://replica2:8002/eureka/ #注册到另一个Eureka注册中心
    fetch-registry: true
    register-with-eureka: true